### ISSUE TITLE
Uncaught Error: Requested measurement of a line that is not currently rendered

### ISSUE THREAD

**Issue by green3g** [facebooknuclide/hyperclick#16]
[Enter steps to reproduce:]

1. Using split-diff package enable

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [hyperclick](https://github.com/facebooknuclide/hyperclick) package 0.0.40

### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At C:\Users\groemhildt\AppData\Local\atom\app-1.19.0-beta1\resources\app\src\text-editor-component.js:2137

Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/text-editor-component.js:2135:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/text-editor-component.js:2128:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/text-editor-component.js:373:16)
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/text-editor-component.js:2239:18)
    at TextEditorComponent.screenPositionForMouseEvent (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/text-editor-component.js:1842:23)
    at HyperclickForTextEditor._getMousePositionAsBufferPosition (/packages/hyperclick/lib/HyperclickForTextEditor.js:298:38)
    at HyperclickForTextEditor._isMouseAtLastWordRange (/packages/hyperclick/lib/HyperclickForTextEditor.js:328:43)
    at HyperclickForTextEditor._onMouseMove (/packages/hyperclick/lib/HyperclickForTextEditor.js:178:16)
```

### Commands

```
     -9:03.1.0 intentions:highlight (input.hidden-input)
     -9:03.0 core:paste (input.hidden-input)
     -9:02.6.0 intentions:highlight (input.hidden-input)
     -9:02.4.0 core:save (input.hidden-input)
     -6:08.3.0 intentions:highlight (input.hidden-input)
     -6:08.2.0 core:save (input.hidden-input)
     -0:59.5.0 tree-view:open-selected-entry-left (span.name.icon.js-icon.medium-yellow)
     -0:56.4.0 intentions:highlight (input.hidden-input)
     -0:56 command-palette:toggle (input.hidden-input)
  3x -0:52.8.0 core:move-down (input.hidden-input)
     -0:51 core:confirm (input.hidden-input)
     -0:51 split-diff:toggle (input.hidden-input)
     -0:17.4.0 tree-view:open-selected-entry-right (span.name.icon.js-icon.medium-yellow)
     -0:13.9.0 intentions:highlight (input.hidden-input)
     -0:13.5.0 command-palette:toggle (input.hidden-input)
     -0:28.3.0 split-diff:enable (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-jinja2 0.6.0 
atom-typescript 11.0.3 
autocomplete-python 1.9.0 
busy-signal 1.4.3 
docblockr 0.10.5 
file-icons 2.1.7 
git-plus 7.9.3 
git-time-machine 1.5.9 
go-debug 1.4.3 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
kite 0.27.0 
language-batch 0.4.0 
language-markdown 0.23.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-pycodestyle 2.0.2 
linter-ui-default 1.6.2 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
platformio-ide-terminal 2.5.1 
split-diff 1.4.3 
```

**Comment by hansonw** [comment]
It seems like split-diff breaks one of the core editor APIs (screenPositionForMouseEvent). I'd file an issue there to fix that, sorry
