### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by umpirsky** [facebooknuclide/hyperclick#25]
I just created file with:

```php
<?php

namespace Foo\CoreBundle\Bar\Baz;


class Foo
```
content.

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.2
**Thrown From**: [hyperclick](https://github.com/facebooknuclide/hyperclick) package 0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'firstChild' of undefined

```
At /usr/share/atom-beta/resources/app/src/text-editor-component.js:2097

TypeError: Cannot read property 'firstChild' of undefined
    at TextEditorComponent.measureLongestLineWidth (/usr/share/atom-beta/resources/app/src/text-editor-component.js:2097:112)
    at TextEditorComponent.measureContentDuringUpdateSync (/usr/share/atom-beta/resources/app/src/text-editor-component.js:372:16)
    at TextEditorComponent.screenPositionForPixelPosition (/usr/share/atom-beta/resources/app/src/text-editor-component.js:2239:18)
    at TextEditorComponent.screenPositionForMouseEvent (/usr/share/atom-beta/resources/app/src/text-editor-component.js:1842:23)
    at t.default._getMousePositionAsBufferPosition (/packages/hyperclick/index.js:1:161291)
    at t.default._onMouseMove (/packages/hyperclick/index.js:1:159272)
```

### Commands

```
     -0:15 intentions:highlight (input.hidden-input)
     -0:14.6.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:14.4.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
  2x -0:10.3.0 core:move-up (input.hidden-input)
     -0:09.8.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:09.5.0 editor:select-to-end-of-line (input.hidden-input)
     -0:09.3.0 intentions:highlight (input.hidden-input)
     -0:09.2.0 core:copy (input.hidden-input)
     -0:08.8.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:08.6.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
  2x -0:07.6.0 core:move-down (input.hidden-input)
  2x -0:06.4.0 core:move-up (input.hidden-input)
     -0:05.5.0 docblockr:parse-enter (input.hidden-input)
     -0:05.5.0 editor:newline (input.hidden-input)
     -0:04.4.0 docblockr:parse-enter (input.hidden-input)
     -0:04.4.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
busy-signal 1.4.3 
change-case 0.6.5 
docblockr 0.11.0 
hyperclick 0.1.2 
intentions 1.1.2 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-jshint 3.1.5 
linter-php 1.3.2 
linter-ui-default 1.6.2 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.0 
php-twig 4.0.0 
project-manager 3.3.5 
```

**Comment by hansonw** [comment]
Can you update to 1.19.0-beta4 to see if this persists? There's been a number of patches to the text editor since beta1.

**Comment by umpirsky** [comment]
Will do, thanks.

**Comment by hansonw** [comment]
I managed to repro #24, so I think it's the same issue. Closing in favor of it
