### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by tjmehta** [facebooknuclide/hyperclick#31]
Steps to possibly reproduce:

1. I am using hyperclyck with a non-nuclide atom.
2. I cmd+clicked a class (react-component) that was being imported by another file.
3. It opened the same file in another pane showing where the module was being imported.
4. I then cmd+clicked the location of the import to open that file.
5. Once I opened that file I was receiving this error every time I hovered over the original file where I originally cmd+clicked the class name.

**Atom**: 1.19.0-beta5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [hyperclick](https://github.com/facebooknuclide/hyperclick) package 0.1.3

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/decoration-manager.js:191

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/decoration-manager.js:183:27)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1810:43)
    at new Selection (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/selection.js:35:43)
    at TextEditor.module.exports.TextEditor.addSelection (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2646:25)
    at /Applications/AtomLite/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker-layer.js:79:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:417:28)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:217:25)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker-layer.js:105:58)
    at TextEditor.module.exports.TextEditor.addSelectionForBufferRange (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2320:40)
    at TextEditor.module.exports.TextEditor.createLastSelectionIfNeeded (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2712:27)
    at TextEditor.module.exports.TextEditor.getLastCursor (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2126:18)
    at t.wordAtPosition (/packages/hyperclick/index.js:1:141003)
    at t.default._onMouseMove (/packages/hyperclick/index.js:1:158239)
```

### Commands

```
     -6:42.9.0 core:backspace (input.hidden-input)
     -6:36.1.0 core:save (input.hidden-input)
     -6:26.4.0 editor:select-to-beginning-of-word (input.hidden-input)
     -6:24.8.0 core:save (input.hidden-input)
     -0:19.1.0 find-and-replace:use-selection-as-find-pattern (input.hidden-input)
     -0:18.5.0 find-and-replace:find-previous (input.hidden-input)
```

### Non-Core Packages

```
atom-sublime-monokai-syntax 0.4.4 
auto-detect-indentation 1.3.0 
autocomplete-modules 1.6.10 
busy-signal 1.4.3 
Dependents 1.6.6 
flow-ide 1.6.0 
git-blame 1.1.1 
git-plus 7.9.3 
greppage 0.1.0 
hey-pane 1.0.0 
highlight-selected 0.13.1 
hyperclick 0.1.3 
intentions 1.1.5 
js-hyperclick 1.11.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
nuclide 0.242.66273750 
quick-file-actions 0.2.1 
terminal-plus 0.14.5 
tree-view-git-modified 0.7.3 
```

**Comment by hansonw** [comment]
I think this is fixed in the latest Atom release.
