### ISSUE TITLE
Failed to activate the hyperclick package

### ISSUE THREAD

**Issue by Walt9Z** [facebooknuclide/hyperclick#32]
Just installed version 1.19.0...

Cannot read property 'getDomNode' of undefined

See attached [Stack Trace](https://github.com/facebooknuclide/hyperclick/files/1215093/StackTrace.txt)

**Comment by hansonw** [comment]
Which version of Hyperclick is this? This hasn't been an issue for quite a while now.

**Comment by murali44** [comment]
I'm seeing this issue as well. Version: 0.1.3

Error: Package not initialized
    at Object.e.(anonymous function) [as observeTextEditor] (/home/parallels/.atom/packages/hyperclick/index.js:1:152957)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:353:69)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:187:16)
    at /usr/share/atom/resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:548:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100 :18)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by hansonw** [comment]
@murali44 That's actually a different issue. Are you on the latest Atom version? The last report was using a very outdated version: https://github.com/facebooknuclide/hyperclick/issues/17

**Comment by murali44** [comment]
@hansonw Yup! upgrading to the latest version of atom fixed it. Thanks.

**Comment by justinligraph** [comment]
I saw same problem. My atom is 1.19.0. What I did is I deinstalled hyperlink and reinstalled it. It works now.

**Comment by woozy** [comment]
Same in here! After upgrading to Atom 1.19.

**Comment by martynchamberlin** [comment]
Same here. Atom 1.19.0 X 64.

**Comment by hansonw** [comment]
In the past this issue has been solved by clearing the APM cache, uninstalling hyperclick, and then reinstalling it. Can you guys try this? https://github.com/facebooknuclide/hyperclick/issues/20#issuecomment-312954082

**Comment by tonybengue** [comment]
Same here on the atom portable version.

**Comment by martynchamberlin** [comment]
@hansonw I confirmed that that seemed to have fixed it for me. Thanks!
