### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zenopopovici** [facebooknuclide/hyperclick#35]
[Enter steps to reproduce:]

1. Create new file
2. Paste some JSON

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [hyperclick](https://github.com/facebooknuclide/hyperclick) package 0.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2367

TypeError: Cannot read property 'length' of undefined
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2367:33)
    at TextEditorComponent.screenPositionForMouseEvent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1954:23)
    at t.default._getMousePositionAsBufferPosition (/packages/hyperclick/index.js:1:160281)
    at t.default._onMouseMove (/packages/hyperclick/index.js:1:158262)
```

### Commands

```
     -0:18.9.0 application:new-file (div.panels-item)
     -0:17.7.0 core:paste (input.hidden-input)
     -0:09.6.0 core:select-all (input.hidden-input)
     -0:05.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-php 1.1.1 
aligner-stylus 1.1.0 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-cursor-indent 0.1.1 
atom-vim-keymap 1.0.1 
atom-wrap-in-tag 0.6.0 
autocomplete-nunjucks 0.5.0 
autocomplete-php 0.3.7 
blame 0.12.0 
busy-signal 1.4.3 
change-case 0.6.5 
copy-filename 1.1.0 
docblockr 0.11.0 
double-tag 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
es-identifier-highlight 0.4.3 
escape-utils 0.5.3 
file-type-icons 1.3.4 
filesize 3.0.0 
fold-comments 0.6.0 
git-blame 1.2.2 
git-history 3.3.0 
highlight-column 0.5.4 
highlight-selected 0.13.1 
hyperclick 0.1.3 
indent-toggle-on-paste 0.1.3 
intentions 1.1.5 
keybinding-cheatsheet 0.1.1 
language-babel 2.73.0 
language-gitignore 0.3.0 
language-nunjucks 4.1.0 
language-svg 0.9.2 
language-vue 0.23.1 
less-than-slash 0.17.0 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-htmlhint 1.3.3 
linter-jsonlint 1.3.0 
linter-php 1.4.0 
linter-stylint 2.2.8 
linter-ui-default 1.6.8 
linter-xo 0.23.1 
markdown-table-editor 0.6.3 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
minimap-selection 4.5.0 
npm-outdated 0.6.0 
pathr 1.0.1 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
php-integrator-symbol-viewer 0.6.4 
pigments 0.40.2 
platformio-ide-terminal 2.6.0 
project-manager 3.3.5 
qolor 0.4.2 
regex-railroad-diagram 0.19.3 
remember-file-positions 0.2.3 
remember-folds 0.3.0 
Remote-FTP 1.1.4 
resize-indent 0.3.0 
snippets-editor 1.0.0 
Stylus 3.1.1 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.11.0 
sync-settings 0.8.3 
tab-numbers 0.6.0 
tabs-to-spaces 1.0.3 
todo-show 2.0.0 
toggle-quotes 1.0.1 
vim-mode-plus 1.3.3 
w3c-validation 0.4.0 
zentabs 0.8.8 
```

**Comment by hansonw** [comment]
Can you see if this is fixed in https://github.com/atom/atom/releases/tag/v1.19.6?
