### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by mattdevoni** [facebooknuclide/hyperclick#46]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [hyperclick](https://github.com/facebook-atom/hyperclick) package 0.1.5

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At C:\Users\malarconp\AppData\Local\atom\app-1.25.0\resources\app\src\text-editor-component.js:2399

TypeError: Cannot match against 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:2399:65)
    at TextEditorComponent.screenPositionForMouseEvent (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:1964:23)
    at t.default._getMousePositionAsBufferPosition (/packages/hyperclick/index.js:1:160492)
    at t.default._onMouseMove (/packages/hyperclick/index.js:1:158466)
```

### Commands

```
     -0:54.9.0 intentions:highlight (input.hidden-input)
     -0:54.9.0 core:undo (input.hidden-input)
     -0:54.7.0 intentions:highlight (input.hidden-input)
     -0:54.7.0 core:undo (input.hidden-input)
     -0:53.5.0 editor:consolidate-selections (input.hidden-input)
     -0:53.5.0 core:cancel (input.hidden-input)
     -0:52.6.0 intentions:highlight (input.hidden-input)
     -0:52.4.0 core:undo (input.hidden-input)
     -0:46.7.0 intentions:highlight (input.hidden-input)
  3x -0:46.6.0 core:redo (input.hidden-input)
  5x -0:45.4.0 core:undo (input.hidden-input)
 43x -0:44 core:redo (input.hidden-input)
     -0:41.7.0 intentions:highlight (input.hidden-input)
  2x -0:41.6.0 core:undo (input.hidden-input)
     -0:06.9.0 intentions:highlight (input.hidden-input)
     -0:06.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
artisan 0.3.2 
autoclose-html 0.23.0 
blade-snippets 0.2.0 
blade-spacer 0.4.2 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.16 
hyperclick 0.1.5 
hyperclick-php 0.2.1 
intentions 1.1.5 
js-hyperclick 1.13.0 
language-blade 0.38.0 
language-vue 0.23.1 
language-vue-component 0.5.0 
laravel 0.7.1 
laravel-snippets 2.1.0 
lint-sass-vue 1.0.5 
linter 2.2.0 
linter-ui-default 1.6.10 
php-hyperclick 1.2.1 
vue-autocompile 0.0.6 
vue-hyperclick 0.2.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by hansonw** [comment]
see: https://github.com/atom/atom/issues/15682
